"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import finam_grpc_client.proto.grpc.tradeapi.v1.side_pb2
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import google.type.decimal_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AccountTrade(google.protobuf.message.Message):
    """Информация о сделке"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRADE_ID_FIELD_NUMBER: builtins.int
    SYMBOL_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    SIDE_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    ORDER_ID_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    COMMENT_FIELD_NUMBER: builtins.int
    trade_id: builtins.str
    """Идентификатор сделки"""
    symbol: builtins.str
    """Символ инструмента"""
    side: finam_grpc_client.proto.grpc.tradeapi.v1.side_pb2.Side.ValueType
    """Сторона сделки (long или short)"""
    order_id: builtins.str
    """Идентификатор заявки"""
    account_id: builtins.str
    """Идентификатор аккаунта"""
    comment: builtins.str
    """Метка заявки. (максимум 128 символов)"""
    @property
    def price(self) -> google.type.decimal_pb2.Decimal:
        """Цена исполнения"""

    @property
    def size(self) -> google.type.decimal_pb2.Decimal:
        """Размер в шт."""

    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Метка времени"""

    def __init__(
        self,
        *,
        trade_id: builtins.str = ...,
        symbol: builtins.str = ...,
        price: google.type.decimal_pb2.Decimal | None = ...,
        size: google.type.decimal_pb2.Decimal | None = ...,
        side: finam_grpc_client.proto.grpc.tradeapi.v1.side_pb2.Side.ValueType = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        order_id: builtins.str = ...,
        account_id: builtins.str = ...,
        comment: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["price", b"price", "size", b"size", "timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id", "comment", b"comment", "order_id", b"order_id", "price", b"price", "side", b"side", "size", b"size", "symbol", b"symbol", "timestamp", b"timestamp", "trade_id", b"trade_id"]) -> None: ...

Global___AccountTrade: typing_extensions.TypeAlias = AccountTrade
