"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import finam_grpc_client.proto.grpc.tradeapi.v1.side_pb2
import finam_grpc_client.proto.grpc.tradeapi.v1.trade_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import google.type.decimal_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

if sys.version_info >= (3, 13):
    from warnings import deprecated
else:
    from typing_extensions import deprecated

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _OrderType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OrderTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OrderType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ORDER_TYPE_UNSPECIFIED: _OrderType.ValueType  # 0
    """Значение не указано"""
    ORDER_TYPE_MARKET: _OrderType.ValueType  # 1
    """Рыночная"""
    ORDER_TYPE_LIMIT: _OrderType.ValueType  # 2
    """Лимитная"""
    ORDER_TYPE_STOP: _OrderType.ValueType  # 3
    """Стоп заявка рыночная"""
    ORDER_TYPE_STOP_LIMIT: _OrderType.ValueType  # 4
    """Стоп заявка лимитная"""
    ORDER_TYPE_MULTI_LEG: _OrderType.ValueType  # 5
    """Мульти лег заявка"""

class OrderType(_OrderType, metaclass=_OrderTypeEnumTypeWrapper):
    """Тип заявки"""

ORDER_TYPE_UNSPECIFIED: OrderType.ValueType  # 0
"""Значение не указано"""
ORDER_TYPE_MARKET: OrderType.ValueType  # 1
"""Рыночная"""
ORDER_TYPE_LIMIT: OrderType.ValueType  # 2
"""Лимитная"""
ORDER_TYPE_STOP: OrderType.ValueType  # 3
"""Стоп заявка рыночная"""
ORDER_TYPE_STOP_LIMIT: OrderType.ValueType  # 4
"""Стоп заявка лимитная"""
ORDER_TYPE_MULTI_LEG: OrderType.ValueType  # 5
"""Мульти лег заявка"""
Global___OrderType: typing_extensions.TypeAlias = OrderType

class _TimeInForce:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TimeInForceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TimeInForce.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TIME_IN_FORCE_UNSPECIFIED: _TimeInForce.ValueType  # 0
    """Значение не указано"""
    TIME_IN_FORCE_DAY: _TimeInForce.ValueType  # 1
    """До конца дня"""
    TIME_IN_FORCE_GOOD_TILL_CANCEL: _TimeInForce.ValueType  # 2
    """Действителен до отмены"""
    TIME_IN_FORCE_GOOD_TILL_CROSSING: _TimeInForce.ValueType  # 3
    """Действителен до пересечения"""
    TIME_IN_FORCE_EXT: _TimeInForce.ValueType  # 4
    """Внебиржевая торговля"""
    TIME_IN_FORCE_ON_OPEN: _TimeInForce.ValueType  # 5
    """На открытии биржи"""
    TIME_IN_FORCE_ON_CLOSE: _TimeInForce.ValueType  # 6
    """На закрытии биржи"""
    TIME_IN_FORCE_IOC: _TimeInForce.ValueType  # 7
    """Исполнить немедленно или отменить"""
    TIME_IN_FORCE_FOK: _TimeInForce.ValueType  # 8
    """Исполнить полностью или отменить"""

class TimeInForce(_TimeInForce, metaclass=_TimeInForceEnumTypeWrapper):
    """Срок действия заявки"""

TIME_IN_FORCE_UNSPECIFIED: TimeInForce.ValueType  # 0
"""Значение не указано"""
TIME_IN_FORCE_DAY: TimeInForce.ValueType  # 1
"""До конца дня"""
TIME_IN_FORCE_GOOD_TILL_CANCEL: TimeInForce.ValueType  # 2
"""Действителен до отмены"""
TIME_IN_FORCE_GOOD_TILL_CROSSING: TimeInForce.ValueType  # 3
"""Действителен до пересечения"""
TIME_IN_FORCE_EXT: TimeInForce.ValueType  # 4
"""Внебиржевая торговля"""
TIME_IN_FORCE_ON_OPEN: TimeInForce.ValueType  # 5
"""На открытии биржи"""
TIME_IN_FORCE_ON_CLOSE: TimeInForce.ValueType  # 6
"""На закрытии биржи"""
TIME_IN_FORCE_IOC: TimeInForce.ValueType  # 7
"""Исполнить немедленно или отменить"""
TIME_IN_FORCE_FOK: TimeInForce.ValueType  # 8
"""Исполнить полностью или отменить"""
Global___TimeInForce: typing_extensions.TypeAlias = TimeInForce

class _StopCondition:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StopConditionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_StopCondition.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    STOP_CONDITION_UNSPECIFIED: _StopCondition.ValueType  # 0
    """Значение не указано"""
    STOP_CONDITION_LAST_UP: _StopCondition.ValueType  # 1
    """Цена срабатывания больше текущей цены"""
    STOP_CONDITION_LAST_DOWN: _StopCondition.ValueType  # 2
    """Цена срабатывания меньше текущей цены"""

class StopCondition(_StopCondition, metaclass=_StopConditionEnumTypeWrapper):
    """Условие срабатывания стоп заявки"""

STOP_CONDITION_UNSPECIFIED: StopCondition.ValueType  # 0
"""Значение не указано"""
STOP_CONDITION_LAST_UP: StopCondition.ValueType  # 1
"""Цена срабатывания больше текущей цены"""
STOP_CONDITION_LAST_DOWN: StopCondition.ValueType  # 2
"""Цена срабатывания меньше текущей цены"""
Global___StopCondition: typing_extensions.TypeAlias = StopCondition

class _OrderStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OrderStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OrderStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ORDER_STATUS_UNSPECIFIED: _OrderStatus.ValueType  # 0
    """Неопределенное значение"""
    ORDER_STATUS_NEW: _OrderStatus.ValueType  # 1
    """Новая заявка"""
    ORDER_STATUS_PARTIALLY_FILLED: _OrderStatus.ValueType  # 2
    """Частично исполненная"""
    ORDER_STATUS_FILLED: _OrderStatus.ValueType  # 3
    """Исполненная"""
    ORDER_STATUS_DONE_FOR_DAY: _OrderStatus.ValueType  # 4
    """Действует в течение дня"""
    ORDER_STATUS_CANCELED: _OrderStatus.ValueType  # 5
    """Отменена"""
    ORDER_STATUS_REPLACED: _OrderStatus.ValueType  # 6
    """Заменена на другую"""
    ORDER_STATUS_PENDING_CANCEL: _OrderStatus.ValueType  # 7
    """Ожидает отмены"""
    ORDER_STATUS_REJECTED: _OrderStatus.ValueType  # 9
    """Отклонена"""
    ORDER_STATUS_SUSPENDED: _OrderStatus.ValueType  # 10
    """Приостановлена"""
    ORDER_STATUS_PENDING_NEW: _OrderStatus.ValueType  # 11
    """В ожидании новой"""
    ORDER_STATUS_EXPIRED: _OrderStatus.ValueType  # 13
    """Истекла"""
    ORDER_STATUS_FAILED: _OrderStatus.ValueType  # 16
    """Ошибка"""
    ORDER_STATUS_FORWARDING: _OrderStatus.ValueType  # 17
    """Пересылка"""
    ORDER_STATUS_WAIT: _OrderStatus.ValueType  # 18
    """Ожидает"""
    ORDER_STATUS_DENIED_BY_BROKER: _OrderStatus.ValueType  # 19
    """Отклонено брокером"""
    ORDER_STATUS_REJECTED_BY_EXCHANGE: _OrderStatus.ValueType  # 20
    """Отклонено биржей"""
    ORDER_STATUS_WATCHING: _OrderStatus.ValueType  # 21
    """Наблюдение"""
    ORDER_STATUS_EXECUTED: _OrderStatus.ValueType  # 22
    """Исполнена"""
    ORDER_STATUS_DISABLED: _OrderStatus.ValueType  # 23
    """Отключена"""
    ORDER_STATUS_LINK_WAIT: _OrderStatus.ValueType  # 24
    """Ожидание ссылки"""
    ORDER_STATUS_SL_GUARD_TIME: _OrderStatus.ValueType  # 27
    """Защитное время SL"""
    ORDER_STATUS_SL_EXECUTED: _OrderStatus.ValueType  # 28
    """Исполнена по SL"""
    ORDER_STATUS_SL_FORWARDING: _OrderStatus.ValueType  # 29
    """Пересылка SL"""
    ORDER_STATUS_TP_GUARD_TIME: _OrderStatus.ValueType  # 30
    """Защитное время TP"""
    ORDER_STATUS_TP_EXECUTED: _OrderStatus.ValueType  # 31
    """Исполнена по TP"""
    ORDER_STATUS_TP_CORRECTION: _OrderStatus.ValueType  # 32
    """Коррекция TP"""
    ORDER_STATUS_TP_FORWARDING: _OrderStatus.ValueType  # 33
    """Пересылка TP"""
    ORDER_STATUS_TP_CORR_GUARD_TIME: _OrderStatus.ValueType  # 34
    """Коррекция TP в защитное время"""

class OrderStatus(_OrderStatus, metaclass=_OrderStatusEnumTypeWrapper):
    """Статус заявки"""

ORDER_STATUS_UNSPECIFIED: OrderStatus.ValueType  # 0
"""Неопределенное значение"""
ORDER_STATUS_NEW: OrderStatus.ValueType  # 1
"""Новая заявка"""
ORDER_STATUS_PARTIALLY_FILLED: OrderStatus.ValueType  # 2
"""Частично исполненная"""
ORDER_STATUS_FILLED: OrderStatus.ValueType  # 3
"""Исполненная"""
ORDER_STATUS_DONE_FOR_DAY: OrderStatus.ValueType  # 4
"""Действует в течение дня"""
ORDER_STATUS_CANCELED: OrderStatus.ValueType  # 5
"""Отменена"""
ORDER_STATUS_REPLACED: OrderStatus.ValueType  # 6
"""Заменена на другую"""
ORDER_STATUS_PENDING_CANCEL: OrderStatus.ValueType  # 7
"""Ожидает отмены"""
ORDER_STATUS_REJECTED: OrderStatus.ValueType  # 9
"""Отклонена"""
ORDER_STATUS_SUSPENDED: OrderStatus.ValueType  # 10
"""Приостановлена"""
ORDER_STATUS_PENDING_NEW: OrderStatus.ValueType  # 11
"""В ожидании новой"""
ORDER_STATUS_EXPIRED: OrderStatus.ValueType  # 13
"""Истекла"""
ORDER_STATUS_FAILED: OrderStatus.ValueType  # 16
"""Ошибка"""
ORDER_STATUS_FORWARDING: OrderStatus.ValueType  # 17
"""Пересылка"""
ORDER_STATUS_WAIT: OrderStatus.ValueType  # 18
"""Ожидает"""
ORDER_STATUS_DENIED_BY_BROKER: OrderStatus.ValueType  # 19
"""Отклонено брокером"""
ORDER_STATUS_REJECTED_BY_EXCHANGE: OrderStatus.ValueType  # 20
"""Отклонено биржей"""
ORDER_STATUS_WATCHING: OrderStatus.ValueType  # 21
"""Наблюдение"""
ORDER_STATUS_EXECUTED: OrderStatus.ValueType  # 22
"""Исполнена"""
ORDER_STATUS_DISABLED: OrderStatus.ValueType  # 23
"""Отключена"""
ORDER_STATUS_LINK_WAIT: OrderStatus.ValueType  # 24
"""Ожидание ссылки"""
ORDER_STATUS_SL_GUARD_TIME: OrderStatus.ValueType  # 27
"""Защитное время SL"""
ORDER_STATUS_SL_EXECUTED: OrderStatus.ValueType  # 28
"""Исполнена по SL"""
ORDER_STATUS_SL_FORWARDING: OrderStatus.ValueType  # 29
"""Пересылка SL"""
ORDER_STATUS_TP_GUARD_TIME: OrderStatus.ValueType  # 30
"""Защитное время TP"""
ORDER_STATUS_TP_EXECUTED: OrderStatus.ValueType  # 31
"""Исполнена по TP"""
ORDER_STATUS_TP_CORRECTION: OrderStatus.ValueType  # 32
"""Коррекция TP"""
ORDER_STATUS_TP_FORWARDING: OrderStatus.ValueType  # 33
"""Пересылка TP"""
ORDER_STATUS_TP_CORR_GUARD_TIME: OrderStatus.ValueType  # 34
"""Коррекция TP в защитное время"""
Global___OrderStatus: typing_extensions.TypeAlias = OrderStatus

class _ValidBefore:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ValidBeforeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ValidBefore.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    VALID_BEFORE_UNSPECIFIED: _ValidBefore.ValueType  # 0
    """Значение не указано"""
    VALID_BEFORE_END_OF_DAY: _ValidBefore.ValueType  # 1
    """До конца торгового дня"""
    VALID_BEFORE_GOOD_TILL_CANCEL: _ValidBefore.ValueType  # 2
    """До отмены"""
    VALID_BEFORE_GOOD_TILL_DATE: _ValidBefore.ValueType  # 3
    """До указанной даты-времени. Данный тип на текущий момент не поддерживается при выставлении заявки"""

class ValidBefore(_ValidBefore, metaclass=_ValidBeforeEnumTypeWrapper):
    """Срок действия условной заявки"""

VALID_BEFORE_UNSPECIFIED: ValidBefore.ValueType  # 0
"""Значение не указано"""
VALID_BEFORE_END_OF_DAY: ValidBefore.ValueType  # 1
"""До конца торгового дня"""
VALID_BEFORE_GOOD_TILL_CANCEL: ValidBefore.ValueType  # 2
"""До отмены"""
VALID_BEFORE_GOOD_TILL_DATE: ValidBefore.ValueType  # 3
"""До указанной даты-времени. Данный тип на текущий момент не поддерживается при выставлении заявки"""
Global___ValidBefore: typing_extensions.TypeAlias = ValidBefore

@deprecated("""This message has been marked as deprecated using proto message options.""")
@typing.final
class OrderTradeRequest(google.protobuf.message.Message):
    """Запрос подписки на собственные заявки и сделки. Стрим"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Action:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ActionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[OrderTradeRequest._Action.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        ACTION_SUBSCRIBE: OrderTradeRequest._Action.ValueType  # 0
        """Подписаться"""
        ACTION_UNSUBSCRIBE: OrderTradeRequest._Action.ValueType  # 1
        """Отписаться"""

    class Action(_Action, metaclass=_ActionEnumTypeWrapper):
        """Доступные действия"""

    ACTION_SUBSCRIBE: OrderTradeRequest.Action.ValueType  # 0
    """Подписаться"""
    ACTION_UNSUBSCRIBE: OrderTradeRequest.Action.ValueType  # 1
    """Отписаться"""

    class _DataType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _DataTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[OrderTradeRequest._DataType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        DATA_TYPE_ALL: OrderTradeRequest._DataType.ValueType  # 0
        """Все: заявки и сделки"""
        DATA_TYPE_ORDERS: OrderTradeRequest._DataType.ValueType  # 1
        """Заявки"""
        DATA_TYPE_TRADES: OrderTradeRequest._DataType.ValueType  # 2
        """Сделки"""

    class DataType(_DataType, metaclass=_DataTypeEnumTypeWrapper):
        """Тип подписки"""

    DATA_TYPE_ALL: OrderTradeRequest.DataType.ValueType  # 0
    """Все: заявки и сделки"""
    DATA_TYPE_ORDERS: OrderTradeRequest.DataType.ValueType  # 1
    """Заявки"""
    DATA_TYPE_TRADES: OrderTradeRequest.DataType.ValueType  # 2
    """Сделки"""

    ACTION_FIELD_NUMBER: builtins.int
    DATA_TYPE_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    action: Global___OrderTradeRequest.Action.ValueType
    """Изменение статуса подписки: подписка/отписка"""
    data_type: Global___OrderTradeRequest.DataType.ValueType
    """Подписка только на заявки/ордера или на все сразу"""
    account_id: builtins.str
    """Идентификатор аккаунта"""
    def __init__(
        self,
        *,
        action: Global___OrderTradeRequest.Action.ValueType = ...,
        data_type: Global___OrderTradeRequest.DataType.ValueType = ...,
        account_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id", "action", b"action", "data_type", b"data_type"]) -> None: ...

Global___OrderTradeRequest: typing_extensions.TypeAlias = OrderTradeRequest

@deprecated("""This message has been marked as deprecated using proto message options.""")
@typing.final
class OrderTradeResponse(google.protobuf.message.Message):
    """Список собственных заявок и сделок"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDERS_FIELD_NUMBER: builtins.int
    TRADES_FIELD_NUMBER: builtins.int
    @property
    def orders(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___OrderState]:
        """Заявки"""

    @property
    def trades(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[finam_grpc_client.proto.grpc.tradeapi.v1.trade_pb2.AccountTrade]:
        """Сделки"""

    def __init__(
        self,
        *,
        orders: collections.abc.Iterable[Global___OrderState] | None = ...,
        trades: collections.abc.Iterable[finam_grpc_client.proto.grpc.tradeapi.v1.trade_pb2.AccountTrade] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["orders", b"orders", "trades", b"trades"]) -> None: ...

Global___OrderTradeResponse: typing_extensions.TypeAlias = OrderTradeResponse

@typing.final
class SubscribeOrdersRequest(google.protobuf.message.Message):
    """Запрос подписки на собственные заявки. Стрим"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    """Идентификатор аккаунта"""
    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id"]) -> None: ...

Global___SubscribeOrdersRequest: typing_extensions.TypeAlias = SubscribeOrdersRequest

@typing.final
class SubscribeOrdersResponse(google.protobuf.message.Message):
    """Список собственных заявок"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDERS_FIELD_NUMBER: builtins.int
    @property
    def orders(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___OrderState]:
        """Заявки"""

    def __init__(
        self,
        *,
        orders: collections.abc.Iterable[Global___OrderState] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["orders", b"orders"]) -> None: ...

Global___SubscribeOrdersResponse: typing_extensions.TypeAlias = SubscribeOrdersResponse

@typing.final
class SubscribeTradesRequest(google.protobuf.message.Message):
    """Запрос подписки на собственные сделки. Стрим"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    """Идентификатор аккаунта"""
    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id"]) -> None: ...

Global___SubscribeTradesRequest: typing_extensions.TypeAlias = SubscribeTradesRequest

@typing.final
class SubscribeTradesResponse(google.protobuf.message.Message):
    """Список собственных сделок"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRADES_FIELD_NUMBER: builtins.int
    @property
    def trades(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[finam_grpc_client.proto.grpc.tradeapi.v1.trade_pb2.AccountTrade]:
        """Сделки"""

    def __init__(
        self,
        *,
        trades: collections.abc.Iterable[finam_grpc_client.proto.grpc.tradeapi.v1.trade_pb2.AccountTrade] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["trades", b"trades"]) -> None: ...

Global___SubscribeTradesResponse: typing_extensions.TypeAlias = SubscribeTradesResponse

@typing.final
class GetOrderRequest(google.protobuf.message.Message):
    """Запрос на получение конкретного ордера"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    ORDER_ID_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    """Идентификатор аккаунта"""
    order_id: builtins.str
    """Идентификатор заявки"""
    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
        order_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id", "order_id", b"order_id"]) -> None: ...

Global___GetOrderRequest: typing_extensions.TypeAlias = GetOrderRequest

@typing.final
class Order(google.protobuf.message.Message):
    """Информация о заявке"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    SYMBOL_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    SIDE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    TIME_IN_FORCE_FIELD_NUMBER: builtins.int
    LIMIT_PRICE_FIELD_NUMBER: builtins.int
    STOP_PRICE_FIELD_NUMBER: builtins.int
    STOP_CONDITION_FIELD_NUMBER: builtins.int
    LEGS_FIELD_NUMBER: builtins.int
    CLIENT_ORDER_ID_FIELD_NUMBER: builtins.int
    VALID_BEFORE_FIELD_NUMBER: builtins.int
    COMMENT_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    """Идентификатор аккаунта"""
    symbol: builtins.str
    """Символ инструмента"""
    side: finam_grpc_client.proto.grpc.tradeapi.v1.side_pb2.Side.ValueType
    """ Сторона (long или short)"""
    type: Global___OrderType.ValueType
    """Тип заявки"""
    time_in_force: Global___TimeInForce.ValueType
    """Срок действия заявки"""
    stop_condition: Global___StopCondition.ValueType
    """Необходимо для стоп рыночной и стоп лимитной заявки"""
    client_order_id: builtins.str
    """Уникальный идентификатор заявки. Автоматически генерируется, если не отправлен. (максимум 20 символов)"""
    valid_before: Global___ValidBefore.ValueType
    """Срок действия условной заявки. Заполняется для заявок с типом ORDER_TYPE_STOP, ORDER_TYPE_STOP_LIMIT"""
    comment: builtins.str
    """Метка заявки. (максимум 128 символов)"""
    @property
    def quantity(self) -> google.type.decimal_pb2.Decimal:
        """Количество в шт."""

    @property
    def limit_price(self) -> google.type.decimal_pb2.Decimal:
        """Необходимо для лимитной и стоп лимитной заявки"""

    @property
    def stop_price(self) -> google.type.decimal_pb2.Decimal:
        """Необходимо для стоп рыночной и стоп лимитной заявки"""

    @property
    def legs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Leg]:
        """Необходимо для мульти лег заявки"""

    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
        symbol: builtins.str = ...,
        quantity: google.type.decimal_pb2.Decimal | None = ...,
        side: finam_grpc_client.proto.grpc.tradeapi.v1.side_pb2.Side.ValueType = ...,
        type: Global___OrderType.ValueType = ...,
        time_in_force: Global___TimeInForce.ValueType = ...,
        limit_price: google.type.decimal_pb2.Decimal | None = ...,
        stop_price: google.type.decimal_pb2.Decimal | None = ...,
        stop_condition: Global___StopCondition.ValueType = ...,
        legs: collections.abc.Iterable[Global___Leg] | None = ...,
        client_order_id: builtins.str = ...,
        valid_before: Global___ValidBefore.ValueType = ...,
        comment: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["limit_price", b"limit_price", "quantity", b"quantity", "stop_price", b"stop_price"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id", "client_order_id", b"client_order_id", "comment", b"comment", "legs", b"legs", "limit_price", b"limit_price", "quantity", b"quantity", "side", b"side", "stop_condition", b"stop_condition", "stop_price", b"stop_price", "symbol", b"symbol", "time_in_force", b"time_in_force", "type", b"type", "valid_before", b"valid_before"]) -> None: ...

Global___Order: typing_extensions.TypeAlias = Order

@typing.final
class Leg(google.protobuf.message.Message):
    """Лег"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    SIDE_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    """Символ инструмента"""
    side: finam_grpc_client.proto.grpc.tradeapi.v1.side_pb2.Side.ValueType
    """Сторона"""
    @property
    def quantity(self) -> google.type.decimal_pb2.Decimal:
        """Количество"""

    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
        quantity: google.type.decimal_pb2.Decimal | None = ...,
        side: finam_grpc_client.proto.grpc.tradeapi.v1.side_pb2.Side.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["quantity", b"quantity"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["quantity", b"quantity", "side", b"side", "symbol", b"symbol"]) -> None: ...

Global___Leg: typing_extensions.TypeAlias = Leg

@typing.final
class OrderState(google.protobuf.message.Message):
    """Состояние заявки"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: builtins.int
    EXEC_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    ORDER_FIELD_NUMBER: builtins.int
    TRANSACT_AT_FIELD_NUMBER: builtins.int
    ACCEPT_AT_FIELD_NUMBER: builtins.int
    WITHDRAW_AT_FIELD_NUMBER: builtins.int
    order_id: builtins.str
    """Идентификатор заявки"""
    exec_id: builtins.str
    """Идентификатор исполнения"""
    status: Global___OrderStatus.ValueType
    """Статус заявки"""
    @property
    def order(self) -> Global___Order:
        """Заявка"""

    @property
    def transact_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Дата и время выставления заявки"""

    @property
    def accept_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Дата и время принятия заявки"""

    @property
    def withdraw_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Дата и время  отмены заявки"""

    def __init__(
        self,
        *,
        order_id: builtins.str = ...,
        exec_id: builtins.str = ...,
        status: Global___OrderStatus.ValueType = ...,
        order: Global___Order | None = ...,
        transact_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        accept_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        withdraw_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["accept_at", b"accept_at", "order", b"order", "transact_at", b"transact_at", "withdraw_at", b"withdraw_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["accept_at", b"accept_at", "exec_id", b"exec_id", "order", b"order", "order_id", b"order_id", "status", b"status", "transact_at", b"transact_at", "withdraw_at", b"withdraw_at"]) -> None: ...

Global___OrderState: typing_extensions.TypeAlias = OrderState

@typing.final
class OrdersRequest(google.protobuf.message.Message):
    """Запрос получения списка торговых заявок"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    """Идентификатор аккаунта"""
    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id"]) -> None: ...

Global___OrdersRequest: typing_extensions.TypeAlias = OrdersRequest

@typing.final
class OrdersResponse(google.protobuf.message.Message):
    """Список торговых заявок"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDERS_FIELD_NUMBER: builtins.int
    @property
    def orders(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___OrderState]:
        """Заявки"""

    def __init__(
        self,
        *,
        orders: collections.abc.Iterable[Global___OrderState] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["orders", b"orders"]) -> None: ...

Global___OrdersResponse: typing_extensions.TypeAlias = OrdersResponse

@typing.final
class CancelOrderRequest(google.protobuf.message.Message):
    """Запрос отмены торговой заявки"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    ORDER_ID_FIELD_NUMBER: builtins.int
    account_id: builtins.str
    """Идентификатор аккаунта"""
    order_id: builtins.str
    """Идентификатор заявки"""
    def __init__(
        self,
        *,
        account_id: builtins.str = ...,
        order_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["account_id", b"account_id", "order_id", b"order_id"]) -> None: ...

Global___CancelOrderRequest: typing_extensions.TypeAlias = CancelOrderRequest
