"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetUsageMetricsRequest(google.protobuf.message.Message):
    """Запрос получения текущих метрик использования"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetUsageMetricsRequest: typing_extensions.TypeAlias = GetUsageMetricsRequest

@typing.final
class GetUsageMetricsResponse(google.protobuf.message.Message):
    """Информация о текущих метриках использования"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class QuotaUsage(google.protobuf.message.Message):
        """Квота"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        LIMIT_FIELD_NUMBER: builtins.int
        REMAINING_FIELD_NUMBER: builtins.int
        RESET_TIME_FIELD_NUMBER: builtins.int
        name: builtins.str
        """Название метода"""
        limit: builtins.int
        """Общий лимит по данной квоте."""
        remaining: builtins.int
        """Сколько осталось доступных единиц в текущем окне."""
        @property
        def reset_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
            """Время, когда счетчик квоты будет сброшен (начало нового окна)."""

        def __init__(
            self,
            *,
            name: builtins.str = ...,
            limit: builtins.int = ...,
            remaining: builtins.int = ...,
            reset_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["reset_time", b"reset_time"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["limit", b"limit", "name", b"name", "remaining", b"remaining", "reset_time", b"reset_time"]) -> None: ...

    QUOTAS_FIELD_NUMBER: builtins.int
    @property
    def quotas(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___GetUsageMetricsResponse.QuotaUsage]:
        """Список текущих квот и их использование."""

    def __init__(
        self,
        *,
        quotas: collections.abc.Iterable[Global___GetUsageMetricsResponse.QuotaUsage] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["quotas", b"quotas"]) -> None: ...

Global___GetUsageMetricsResponse: typing_extensions.TypeAlias = GetUsageMetricsResponse
